### ISSUE TITLE
NFT.createSeries issue

### ISSUE THREAD

**Issue by Relfos** [phantasma-io/TOMB#13]
As reported by Iggy:

I have 4 NFT categories.
So I assigned its edition ids this way
Box; 1-3
Hammer: 101-200 (although hammer doesn’t have 100 editions)
Ghost: 201-300 (although ghost doesn’t have 100 editions)
Badge: 301-400
This never works for me.

I had to change it this way.
Box; 1-3
Badge: 5-10
Hammer: 11-50 (although hammer doesn’t have 100 editions)
Ghost: 51-100 (although ghost doesn’t have 100 editions)

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769

**Comment by Relfos** [comment]
After checking, seems it is not a bug or might not be reproduced anymore in latest version of TOMB. 
Closed, will be re-open if more details appear.
