### ISSUE TITLE
Logical Operators Issue

### ISSUE THREAD

**Issue by ShamanBlackout** [phantasma-io/TOMB#17]
**Compiler.Cs line 1142 & 1145:**

-  OperatorKind.Or and OperatorKind.And is "or" and "and" respectively. 

**TombLangLexer.cs line 44:** 

-  Logical Operators are "||" and "&&". 

**Issue:**

- Using either '&&' or "||" will throw an OperatorKind.Unknown , however we cannot use "and" or "or" either since they are not a part of our LogicalOperators.
- This is seen in Compiler.cs line 638 ParseBinaryExpression...

[cond.txt](https://github.com/phantasma-io/TOMB/files/10991442/cond.txt)

**Comment by Relfos** [comment]
The latest commit fixes this, you can now use && and || in expressions.

Note that TOMB current implementation of operator precedence is not the best, you might need to use parenthesis to separate the different parts of a conditional expression.
eg:

if ((x > 5) && (y<2)) will work

if (x > 5 && y<2) probably won't work yet


Check this new test for a working example:
https://github.com/phantasma-io/TOMB/blob/master/Tests/Tests.cs#L387
