### ISSUE TITLE
onMint,onBurn,onSend,onReceive Parameter Clarification

### ISSUE THREAD

**Issue by ShamanBlackout** [phantasma-io/TOMB#25]
As you can see below these triggers MUST take 4 parameters; however, in example files Trigger1 and Trigger 2 , as well as the comment they take 3.

```c#
case "onMint":
case "onBurn":
case "onSend":
case "onReceive": // address, symbol, amount
CheckParameters(name, parameters, new[] { VarKind.Address, VarKind.Address, VarKind.String, VarKind.Number });
break;
```

Clarification needed to know which would be proper usage.  With team's permission will update the Compiler to match 3 parameters if that is the case.

**Comment by Relfos** [comment]
We checked this against this chain code, the correct number of parameters is 4, only the comments are incorrect (the triggers are working with the compiler, some of the existing dapps like Pharming and Ghostmarket already make use of it).
